<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Promise API In JavaScript</title>
</head>
<body>

    <!-- There are 6 static methods in the Promise class. -->
    <script>
        // Promise.all
        /* In JavaScript, the Promise.all method is used to handle multiple promises concurrently.
        It takes an array of promises as input and returns a new promise that resolves to an array 
        of the resolved values when all the input promises are fulfilled. If any of the input promises
        is rejected, the returned promise will be rejected with the reason of the first rejected promise. */

        // we want many promises to execute in parallel and wait until all of them are ready then we can use Promise.all

        // download several URLs in parallel and process the content once they are all done. That’s what Promise.all is for.

        // The syntax is:
        let promise = Promise.all(iterable);

        // Promise.all takes an iterable (usually, an array of promises) and returns a new promise.
        // The new promise resolves when all listed promises are resolved, and the array of their results becomes its result.


        // For Example, the Promise.all below settles after 3 seconds, and then its result is an array [1, 2, 3]:
        Promise.all([
            new Promise(resolve => setTimeout(() => resolve(1), 3000)), // 1
            new Promise(resolve => setTimeout(() => resolve(2), 2000)), // 2
            new Promise(resolve => setTimeout(() => resolve(3), 1000))  // 3
        ]).then(alert); // 1,2,3 when promises are ready: each promise contributes an array member

        // Please note that the order of the resulting array members is the same as in its source promises.
        // Even though the first promise takes the longest time to resolve, it’s still first in the array of results.




        // A bigger example with fetching user information for an array of GitHub users by their names (we could fetch an array of goods by their ids, the logic is identical):
        let names = ['iliakan', 'remy', 'jeresig'];

        // map every url to the promise of the fetch
        let requests = names.map(name => 
            fetch(`https://api.github.com/users/${name}`)
        );

        // Promise.all waits until all jobs are resolved
        Promise.all(requests)
        .then(responses => {
            // all responses are resolved successfully
            for(let response of responses) {
               alert(`${response.url}: ${response.status}`); // shows 200 for every url
            }

            return responses;
        })
        // map array of responses into an array of response.json() to read their content
        .then(responses => Promise.all(responses.map(r => r.json())))
        // all JSON answers are parsed: "users" is the array of them
        .then(users => users.forEach(user => alert(user.name)));




        // If any of the promises is rejected, the promise returned by Promise.all immediately rejects with that error.

        // For Example:
        Promise.all([
            new Promise((resolve, reject) => setTimeout(() => resolve(1), 1000)),
            new Promise((resolve, reject) => setTimeout(() => reject(new Error("Whoops!")), 2000)),
            new Promise((resolve, reject) => setTimeout(() => resolve(3), 3000))
        ])
        .catch(alert); // Error: Whoops!
        
        // Here the second promise rejects in two seconds. That leads to an immediate rejection of Promise.all,
        // so .catch executes: the rejection error becomes the outcome of the entire Promise.all.

        /* In case of an error, other promises are ignored
        If one promise rejects, Promise.all immediately rejects, completely forgetting about the other ones in the list. Their results are ignored.

        For example, if there are multiple fetch calls, like in the example above, and one fails, the others will still continue to execute,
        but Promise.all won’t watch them anymore. They will probably settle, but their results will be ignored. */
    </script>



    <script>
        // Promise.allSettled
        /* Promise.allSettled is a JavaScript method that takes an array of promises and returns a single promise
        that is fulfilled with an array of objects, each representing the outcome of the corresponding promise
        in the input array. The objects in the resulting array have a status property indicating whether the
        promise was fulfilled or rejected, and a value or reason property containing the fulfillment value or rejection reason, respectively.

        Unlike Promise.all, which rejects immediately if any of the input promises is rejected,
        Promise.allSettled waits for all promises to settle (either fulfill or reject) and then returns a
        result array containing the outcome of each individual promise. This makes it useful in scenarios
        where you want to know the outcome of all promises, regardless of whether they were fulfilled or rejected. */

        // we can use Promise.allSettled to get the results of all given promises, even if some of them reject.


        // Promise.allSettled just waits for all promises to settle, regardless of the result. The resulting array has:
        // {status:"fulfilled", value:result} for successful responses,
        // {status:"rejected", reason:error} for errors.


        // For example, we’d like to fetch the information about multiple users. Even if one request fails, we’re still interested in the others.

        // Let’s use Promise.allSettled:
        let urls = [
            'https://api.github.com/users/iliakan',
            'https://api.github.com/users/remy',
            'https://no-such-url'
        ];

        Promise.allSettled(urls.map(url => fetch(url)))
        .then(results => { // (*)
            results.forEach((result, num) => {
            if (result.status == "fulfilled") {
                alert(`${urls[num]}: ${result.value.status}`);
            }
            if (result.status == "rejected") {
                alert(`${urls[num]}: ${result.reason}`);
            }
            });
        });

        // The results in the line (*) above will be:
        /* [
            {status: 'fulfilled', value: ...response...},
            {status: 'fulfilled', value: ...response...},
            {status: 'rejected', reason: ...error object...}
        ] */
        // So for each promise we get its status and value/error.
    </script>



    <script>
        // Promise.race
        // Promise.race hame first settled promise return karta hai chahe to resolve ho ya reject.
        // Similar to Promise.all, but waits only for the first settled promise and gets its result (or error).

        // The syntax is:
        let promise2 = Promise.race(iterable);

        // For Example, here the result will be 1:
        Promise.race([
            new Promise((resolve, reject) => setTimeout(() => resolve(1), 1000)),
            new Promise((resolve, reject) => setTimeout(() => reject(new Error("Whoops!")), 2000)),
            new Promise((resolve, reject) => setTimeout(() => resolve(3), 3000))
        ])
        .then(alert); // 1

        // The first promise here was fastest, so it became the result.
        // After the first settled promise “wins the race”, all further results/errors are ignored.
    </script>



    <script>
        // Promise.any
        /* Promise.any hame first fulfilled promise return karta hai or yadi all promise reject hogi,
        to hame ek array of object return kare ga jisme all promise ki errors store hogi. */

        /* Similar to Promise.race, but waits only for the first fulfilled promise and gets its result.
        If all of the given promises are rejected, then the returned promise is rejected with AggregateError –
        a special error object that stores all promise errors in its errors property. */

        // The syntax is:
        let promise3 = Promise.any(iterable);

        // For Example, here the result will be 1:
        Promise.any([
            new Promise((resolve, reject) => setTimeout(() => reject(new Error("Whoops!")), 1000)),
            new Promise((resolve, reject) => setTimeout(() => resolve(1), 2000)),
            new Promise((resolve, reject) => setTimeout(() => resolve(3), 3000))
        ])
        .then(alert); // 1
        
        // The first promise here was fastest, but it was rejected, so the second promise became the result.
        // After the first fulfilled promise “wins the race”, all further results are ignored.


        // Here’s an example when all promises fail:
        Promise.any([
            new Promise((resolve, reject) => setTimeout(() => reject(new Error("Ouch!")), 1000)),
            new Promise((resolve, reject) => setTimeout(() => reject(new Error("Error!")), 2000))
        ])
        .catch(error => {
            console.log(error.constructor.name); // AggregateError
            console.log(error.errors[0]); // Error: Ouch!
            console.log(error.errors[1]); // Error: Error!
        });

        // As you can see, error objects for failed promises are available in the errors property of the AggregateError object.
    </script>



    <script>
        // Promise.resolve/reject
        // Methods Promise.resolve and Promise.reject are rarely needed in modern code, because async/await syntax makes them somewhat obsolete.
        
        /* Promise.reject is a static method in JavaScript that returns a new Promise object that is rejected
        with a specified reason or error.
        Promise.resolve, which creates a Promise that is resolved with a specified value. */


        // Promise.resolve
        // Promise.resolve(value) creates a resolved promise with the result value.

        // Same as:
        let promise4 = new Promise(resolve => resolve(value));

        // Example
        let resolvedPromise = Promise.resolve('Success');
        resolvedPromise.then(value => {
            console.log(value); // Output: Success
        });


        // The method is used for compatibility, when a function is expected to return a promise.


        // Promise.reject
        // Promise.reject(error) creates a rejected promise with error.

        // Same as:
        let promise5 = new Promise((resolve, reject) => reject(error));

        // Example
        let rejectedPromise = Promise.reject('Error occurred');
        rejectedPromise.catch(error => {
            console.log(error); // Output: Error occurred
        });


        // In practice, this method is almost never used.
    </script>



    <script>
        // Summary
        // There are 6 static methods of Promise class:
        /*
        1.Promise.all(promises) – waits for all promises to resolve and returns an array of their results. If any of the given promises rejects, it becomes the error of Promise.all, and all other results are ignored.

        2. Promise.allSettled(promises) (recently added method) – waits for all promises to settle and returns their results as an array of objects with:

            status: "fulfilled" or "rejected"
            value (if fulfilled) or reason (if rejected).
        
        3. Promise.race(promises) – waits for the first promise to settle, and its result/error becomes the outcome.

        4. Promise.any(promises) (recently added method) – waits for the first promise to fulfill, and its result becomes the outcome. If all of the given promises are rejected, AggregateError becomes the error of Promise.any.

        5. Promise.resolve(value) – makes a resolved promise with the given value.

        6. Promise.reject(error) – makes a rejected promise with the given error. */

        // Of all these, Promise.all is probably the most common in practice.
    </script>
    
</body>
</html>